/**
 * Feature Scaler Parameters (Placeholder)
 * ========================================
 * 
 * This file should be generated by the training script:
 *   python scripts/train_tflite_model.py --data_dir ../data/dreamt
 * 
 * The training script outputs: models/tflite_4class/scaler_params.h
 * Copy that file here to replace this placeholder.
 * 
 * These values are used to normalize features before inference:
 *   scaled_value = (raw_value - FEATURE_MEAN[i]) / FEATURE_SCALE[i]
 */

#ifndef SCALER_PARAMS_H
#define SCALER_PARAMS_H

// Placeholder values - will be replaced by actual values from training
// Feature count should match: 72 features (50 IMU + 22 PPG)
#define N_FEATURES 72
#define N_CLASSES 4

// Placeholder mean values (one per feature)
const float FEATURE_MEAN[N_FEATURES] = {
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
    0.0f, 0.0f
};

// Placeholder scale values (standard deviation)
const float FEATURE_SCALE[N_FEATURES] = {
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
    1.0f, 1.0f
};

// Class names for display
const char* CLASS_NAMES[N_CLASSES] = {
    "Wake", "Light", "Deep", "REM"
};

#endif // SCALER_PARAMS_H

